-- USERS
INSERT INTO users (id, name, email, password) VALUES (1, 'Rea', 'rboylan0@opera.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');
INSERT INTO users (id, name, email, password) VALUES (2, 'Ashlin', 'alavallie1@wp.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');
INSERT INTO users (id, name, email, password) VALUES (3, 'Sancho', 'stimmons2@adobe.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');

-- PROPERTIES
INSERT INTO properties (id, owner_id, title, description, photo_thumbnail, photo_cover, cost_per_night, parking_spaces, num_of_bathrooms, num_of_bedrooms, country, street, city, province, post_code, active) VALUES (1, 1, 'in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 'http://dummyimage.com/213x159.bmp/dddddd/000000', 'http://dummyimage.com/1993x2500.bmp/ff4444/ffffff', 334, 4, 5, 1, 'Palestinian Territory', '63774 Meadow Valley Alley', 'Tayāsīr', 'TK', 15467, true);
INSERT INTO properties (id, owner_id, title, description, photo_thumbnail, photo_cover, cost_per_night, parking_spaces, num_of_bathrooms, num_of_bedrooms, country, street, city, province, post_code, active) VALUES (2, 1, 'nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 'http://dummyimage.com/122x244.bmp/ff4444/ffffff', 'http://dummyimage.com/1541x1873.png/dddddd/000000', 286, 4, 2, 5, 'Russia', '20576 Prairie Rose Pass', 'Ruzayevka', 'RU', '431469', true);
INSERT INTO properties (id, owner_id, title, description, photo_thumbnail, photo_cover, cost_per_night, parking_spaces, num_of_bathrooms, num_of_bedrooms, country, street, city, province, post_code, active) VALUES (3, 2, 'orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.', 'http://dummyimage.com/152x205.jpg/5fa2dd/ffffff', 'http://dummyimage.com/2496x1959.jpg/cc0000/ffffff', 526, 4, 1, 1, 'Canada', '820 Graedel Terrace', 'Agassiz', 'British Columbia', 'B2E', true);

-- RESERVATIONS
INSERT INTO reservations (id, guest_id, property_id, start_date, end_date) VALUES (1, 3, 1, '3/2/2021', '4/12/2020');
INSERT INTO reservations (id, guest_id, property_id, start_date, end_date) VALUES (2, 3, 1, '6/2/2020', '10/7/2020');
INSERT INTO reservations (id, guest_id, property_id, start_date, end_date) VALUES (3, 1, 3, '11/4/2020', '12/13/2020');

-- PROPERTY_REVIEWS
INSERT INTO property_reviews (id, guest_id, reservation_id, property_id, message, rating) VALUES (1, 1, 1, 1, 'Etiam pretium iaculis justo.', 2);
INSERT INTO property_reviews (id, guest_id, reservation_id, property_id, message, rating) VALUES (2, 3, 3, 2, 'Phasellus in felis. Donec semper sapien a libero.', 2);
INSERT INTO property_reviews (id, guest_id, reservation_id, property_id, message, rating) VALUES (3, 3, 2, 1, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 2);
